import { NextIntlClientProvider } from 'next-intl';
import '../globals.css';
import { Metadata } from 'next';
import { getMessages } from 'next-intl/server';
import { ThemeProvider } from '@/provider/ThemeProvider';
import { Locale, routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import { Header } from '../components/header/Header';
import { DownloadPopup } from '../components/downloadPopup/DownloadPopup';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            <div id="download-portal" />
            <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 light:from-gray-100 light:to-white text-white light:text-gray-900 transition-colors duration-300 p-4 md:p-8">
              <Header />
              {children}
              <DownloadPopup />
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default LocaleLayout;
