import './globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="download-portal"></div>
        <div id="root">{children}</div>
      </body>
    </html>
  );
}

export default RootLayout;
