import { NextIntlClientProvider } from 'next-intl';
import './globals.css';
import { Metadata } from 'next';
import { getLocale } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider>
          <div id="download-portal" />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;
